## @file
# Azure Pipeline build file for a build using ubuntu and GCC5.
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: refs/tags/v2.2.0

variables:
- group: architectures-x86-64
- group: tool-chain-ubuntu-gcc

jobs:
- template: Jobs/PrGate.yml@mu_devops
  parameters:
    arch_list: $(arch_list)
    do_ci_build: true
    do_ci_setup: true
    do_pr_eval: false
    packages: MmSupervisorPkg
    target_list: DEBUG,RELEASE,NO-TARGET,NOOPT
    tool_chain_tag: $(tool_chain_tag)
    vm_image: $(vm_image)
    container_build: true
