## @file
# Azure Pipeline build file for a build using ubuntu and GCC
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2020, Hewlett Packard Enterprise Development LP. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
trigger:
- release/202202

schedules:
- cron: "30 9 * * 0"  # Sun/Wed at 2:30AM Pacific
  displayName: Sun Build
  branches:
    include:
    - main
  always: true          # Always build, even if no changes

pr:
- release/202202

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

jobs:
- template: Jobs/PrGate.yml@mu_devops
  parameters:
    arch_list: IA32,X64
    do_ci_build: true
    do_ci_setup: false
    do_pr_eval: false
    packages: MmSupervisorPkg
    target_list: DEBUG,RELEASE,NO-TARGET,NOOPT
    tool_chain_tag: GCC5
    vm_image: ubuntu-latest

