
STM_HOME=$(WORKSPACE)\StmPkg

INC = $(INC) -I $(STM_HOME)\include -I $(WORKSPACE)\MdePkg\include

!INCLUDE $(BASE_TOOLS_PATH)\Source\C\Makefiles\ms.common

APPNAME = GenStm

LIBS = $(LIB_PATH)\Common.lib

OBJECTS = GenStm.obj

!INCLUDE $(BASE_TOOLS_PATH)\Source\C\Makefiles\ms.app
